// Generated by gencpp from file test01/Add.msg
// DO NOT EDIT!


#ifndef TEST01_MESSAGE_ADD_H
#define TEST01_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <test01/AddRequest.h>
#include <test01/AddResponse.h>


namespace test01
{

struct Add
{

typedef AddRequest Request;
typedef AddResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Add
} // namespace test01


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test01::Add > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::test01::Add&) { return value(); }
};

template<>
struct DataType< ::test01::Add > {
  static const char* value()
  {
    return "test01/Add";
  }

  static const char* value(const ::test01::Add&) { return value(); }
};


// service_traits::MD5Sum< ::test01::AddRequest> should match
// service_traits::MD5Sum< ::test01::Add >
template<>
struct MD5Sum< ::test01::AddRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test01::Add >::value();
  }
  static const char* value(const ::test01::AddRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test01::AddRequest> should match
// service_traits::DataType< ::test01::Add >
template<>
struct DataType< ::test01::AddRequest>
{
  static const char* value()
  {
    return DataType< ::test01::Add >::value();
  }
  static const char* value(const ::test01::AddRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test01::AddResponse> should match
// service_traits::MD5Sum< ::test01::Add >
template<>
struct MD5Sum< ::test01::AddResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test01::Add >::value();
  }
  static const char* value(const ::test01::AddResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test01::AddResponse> should match
// service_traits::DataType< ::test01::Add >
template<>
struct DataType< ::test01::AddResponse>
{
  static const char* value()
  {
    return DataType< ::test01::Add >::value();
  }
  static const char* value(const ::test01::AddResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST01_MESSAGE_ADD_H
