// Generated by gencpp from file test01/AddResponse.msg
// DO NOT EDIT!


#ifndef TEST01_MESSAGE_ADDRESPONSE_H
#define TEST01_MESSAGE_ADDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test01
{
template <class ContainerAllocator>
struct AddResponse_
{
  typedef AddResponse_<ContainerAllocator> Type;

  AddResponse_()
    : sum(0)  {
    }
  AddResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::test01::AddResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test01::AddResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddResponse_

typedef ::test01::AddResponse_<std::allocator<void> > AddResponse;

typedef boost::shared_ptr< ::test01::AddResponse > AddResponsePtr;
typedef boost::shared_ptr< ::test01::AddResponse const> AddResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test01::AddResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test01::AddResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test01::AddResponse_<ContainerAllocator1> & lhs, const ::test01::AddResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test01::AddResponse_<ContainerAllocator1> & lhs, const ::test01::AddResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test01

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test01::AddResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test01::AddResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test01::AddResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test01::AddResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test01::AddResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test01::AddResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test01::AddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::test01::AddResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::test01::AddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test01/AddResponse";
  }

  static const char* value(const ::test01::AddResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test01::AddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "    #服务端\n"
"int32 sum\n"
;
  }

  static const char* value(const ::test01::AddResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test01::AddResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test01::AddResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test01::AddResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST01_MESSAGE_ADDRESPONSE_H
